"""rename address

Revision ID: 484d1fc435c3
Revises: ee022281d5b6
Create Date: 2024-09-03 19:53:29.823855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484d1fc435c3'
down_revision = 'ee022281d5b6'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
